# Semester Project

Semester projects may deal with any topic that interests you [the student], as long as it is approved by the instructor.  

Broadly, projects are expected to **identify a research problem** and **develop a designed experiment that is appropriate for solving that problem**. Projects consist of a manuscript and a tutorial that describes the research problem, the experiment design and the treatment design.  

## Learning objectives   

- Apply content learned in class in a real-life problem, connected to the student's research program, including: 
  - Writing the materials and methods section of a paper using statistical notation. 
  - Writing detailed supporting material that clearly connects R code with statistical models. 
  - Interpret the results from the statistical model and connect them to the real-life problem. 

## Partial deadlines

### Project proposal - Due Sunday February 1st at noon CT
Write a 1 or 2 page-long project proposal that (a) includes the background of your problem (i.e., why is this important?) and (b) states your research objective. 

### Written report - Due Wednesday April 20 at 2pm CT for peer review 
Submit a manuscript to one of your classmates. 
The manuscript must include Abstract (250w), Introduction (~500w), M&M (~300-500w), Results (~400w), Discussion (~400w), Conclusions (~100w). 

### Oral presentation - Somewhere between May 1 - May 9 
Prepare a 15 minute presentation of the core aspects of your project. 
Presentations should include at least: 

- Motivation/Background  
- Methods, including a clear and complete description of the statistical model and code 
- Discussion of strengths and weaknesses 
- Conclusions 

### Written report and reproducible tutorial - Due May 15 

- Manuscript must include a publication-ready analysis.  
  - Must include Abstract (250w), Introduction (~500w), M&M (~300-500w), Results (~400w), Discussion (~400w), Conclusions (~100w). 
  - Last paragraph in the Introduction should clearly state the research gap and the research objectives.  
- Publication-ready tutorial/R documentation  
- See evaluation rubric on Canvas. 




