--- 
title: "STAT 799 - Topics in Statistics - Applied linear mixed models in agriculture and life sciences"
author: "Josefina Lacasa"
date: Semester Year #"`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Welcome to STAT 799!  
January 26th, 2026  

## About this course:  

- [About me](https://jlacasa.github.io/) 
- About you: 

```{r message=F, warning=FALSE}
library(tidyverse)
read.csv("../../../students_STAT_799_C.csv") |> 
  filter(degreeProgram != "") %>% 
  ggplot(aes(x = degreeProgram))+
  geom_bar(fill = "#B388EB")+
  theme_bw()+
  scale_y_continuous(breaks = 1:9)+
  theme(panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.title.x = element_blank())
```

- In rounds: What's your major, what do you expect to learn?  

### Logistics  

- [Website](https://stat799.github.io/spring2026/)
- Syllabus
- Statistical programming requirements  
- Rough mindmap of the course (on whiteboard)  
- [Semester project - design your own experiment.](https://stat720.github.io/2025summer/summer2025/notes/semester-project.html)   
- Grades: A (100-89.999999999(!!!)), B (89.99-79.99), C (79.99-69.99), D (69.99-59.99), F (<59.99).
- Attendance policies  
- Semester projects

## Learning goals   

By the end of this course, you should be able to:  
- Be able to identify the treatment design, experiment design, experimental unit and observational unit.  
- Be able to write the statistical model that corresponds to (simple) designed experiments.  
- Be able to write the Materials and Methods section in a paper (or thesis) that describes the designed experiment.  
- Distinguish the benefits/disadvantages of different experiment designs.  


## On notation  

- scalars: $y$, $\sigma$, $\beta_0$  
- vectors: $\mathbf{y} \equiv [y_1, y_2, ..., y_n]'$, $\boldsymbol{\beta} \equiv [\beta_1, \beta_2, ..., \beta_p]'$, $\boldsymbol{u}$  
- matrices: $\mathbf{X}$, $\Sigma$  
- probability distribution: $y \sim N(0, \sigma^2)$, $\mathbf{y} \sim N(\boldsymbol{0}, \sigma^2\mathbf{I})$.     


## For tomorrow    

- Install R and RStudio. 
